"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""

from __future__ import print_function


def euler_002(limit):
    a, b = 0, 1

    while a < limit:
        if not a % 2:
            yield a
        a, b = b, a + b

response = sum(euler_002(4000000))

print(response)
